#!/usr/bin/env python3
"""
manufacturers.py - the official MANUFACTURER_ID registry, committed as data.

Every generated config carries `#define MANUFACTURER_ID XXXX`. The configurator
will not offer a target whose id is absent from the config repo's registry, so
an unregistered id produces a target nobody can install - a failure that shows
up only after the config has been merged. Until now this was checked by hand.

The registry is a markdown table at the root of the config repo:

    |Manufacturer Id|Name|Contact|
    |-|-|-|
    |CUST|'Custom', to be used for homebrew targets||
    |EXMP|Example Robotics Ltd|http://example.invalid/|

`data/manufacturers.json` is a snapshot of that table, generated by --refresh
and committed, so validation works without a config checkout. Unlike
`data/firmware.json` (gitignored, records the local tree it came from), this
file is published: it records the *upstream* repo URL, the commit and a sha256
of the markdown, and never a local path.

The snapshot is taken from the repo's master ref, not from whatever branch is
checked out - a clone sitting on a manufacturer's submission branch would
otherwise bless an id upstream has not merged. `--worktree` overrides.

    # look one up (exit 1 if any is unregistered)
    python manufacturers.py CUST FOSS EXMP

    # regenerate from a local config repo, after reading the printed diff
    python manufacturers.py --refresh [--config PATH] [--ref REF] [--worktree]

For genconfig, the whole API is two functions:

    import manufacturers
    manufacturers.lookup("CUST")   -> Manufacturer(id, name, url, reserved) | None
    manufacturers.check(user_arg)  -> Check(ok, id, name, reserved, reason,
                                            suggestions)

`check()` is the one to call: it normalises the argument, returns the canonical
id to emit, and on failure carries a reason code and near-miss suggestions.
"""

import argparse
import hashlib
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from difflib import get_close_matches
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional, Sequence, Tuple

DATA_FILE = Path(__file__).parent / "data" / "manufacturers.json"

REGISTRY_FILE = "Manufacturers.md"
UPSTREAM_REPO = "https://github.com/betaflight/config"

# Ids the registry sets aside for targets with no manufacturer behind them.
# Registered, so they validate, but a real board should not ship with one -
# CUST in particular is the homebrew placeholder this tool's own examples use.
# Flagged rather than rejected; the caller decides whether to warn.
RESERVED_IDS = ("COMM", "CUST", "FOSS", "LEGA")

# What a well-formed id looks like. Used only to phrase the failure of an id
# that is *not* in the registry ("malformed" reads better than "unregistered"
# for `--manufacturer "Example Robotics"`). It never rejects a row: the registry is the
# authority on what is registered, not this pattern. The repo's own guide says
# 3-4 uppercase characters; every current row is 4.
ID_SHAPE = re.compile(r"^[A-Z0-9]{3,4}$")

SCHEMA = 1


class RegistryError(RuntimeError):
    """The registry data file is missing or unusable."""


class Manufacturer(NamedTuple):
    id: str            # canonical id, as spelled in the registry
    name: str          # manufacturer name ("" if the row left it blank)
    url: str           # contact URL ("" if the row left it blank)
    reserved: bool     # one of RESERVED_IDS


class Check(NamedTuple):
    """
    Result of validating a caller-supplied id.

    ok           - registered, safe to emit
    id           - canonical id to emit (registry spelling when ok, otherwise
                   the normalised input). Emit this, not the raw argument.
    name         - manufacturer name, or None when unregistered
    reserved     - id is a placeholder (CUST/FOSS/COMM/LEGA); ok is still True
    reason       - stable code: "ok" | "empty" | "malformed" | "unregistered"
    suggestions  - close registered ids, for a typo. Possibly empty.
    """
    ok: bool
    id: str
    name: Optional[str]
    reserved: bool
    reason: str
    suggestions: Tuple[str, ...]

    def message(self) -> str:
        """One line suitable for a warning or an error, or "" when ok."""
        if self.ok:
            return ""
        if self.reason == "empty":
            return "MANUFACTURER_ID is empty"
        what = (f"MANUFACTURER_ID {self.id!r} is not a 3-4 character code"
                if self.reason == "malformed" else
                f"MANUFACTURER_ID {self.id!r} is not in the config repo's "
                f"{REGISTRY_FILE}")
        if self.suggestions:
            what += f" (did you mean {', '.join(self.suggestions)}?)"
        return what


class Registry:
    """id -> Manufacturer, plus where the snapshot came from."""

    def __init__(self, data: dict):
        self.schema: int = data.get("schema", 0)
        self.generated: str = data.get("generated", "")
        self.source: Dict[str, str] = dict(data.get("source", {}))
        reserved = set(data.get("reserved", RESERVED_IDS))
        self._by_id: Dict[str, Manufacturer] = {}
        for mid, row in sorted(data.get("manufacturers", {}).items()):
            self._by_id[mid] = Manufacturer(
                id=mid,
                name=row.get("name", ""),
                url=row.get("url", ""),
                reserved=mid in reserved,
            )

    def __len__(self) -> int:
        return len(self._by_id)

    def __contains__(self, mfr_id: object) -> bool:
        return isinstance(mfr_id, str) and normalise(mfr_id) in self._by_id

    def ids(self) -> List[str]:
        return list(self._by_id)

    def lookup(self, mfr_id: str) -> Optional[Manufacturer]:
        return self._by_id.get(normalise(mfr_id))

    def suggest(self, mfr_id: str, n: int = 3) -> Tuple[str, ...]:
        return tuple(get_close_matches(normalise(mfr_id), self._by_id, n=n, cutoff=0.6))

    def check(self, mfr_id: str) -> Check:
        norm = normalise(mfr_id)
        if not norm:
            return Check(False, "", None, False, "empty", ())
        hit = self._by_id.get(norm)
        if hit is not None:
            return Check(True, hit.id, hit.name, hit.reserved, "ok", ())
        reason = "unregistered" if ID_SHAPE.match(norm) else "malformed"
        return Check(False, norm, None, False, reason, self.suggest(norm))

    def provenance(self) -> str:
        """One line naming the snapshot's origin, for a generated header."""
        s = self.source
        rev = s.get("rev") or "unknown"
        if s.get("dirty"):
            rev += "-dirty"
        return (f"{len(self)} ids from {s.get('repo', UPSTREAM_REPO)} "
                f"{s.get('file', REGISTRY_FILE)} @ {rev} "
                f"({s.get('commit_date', '?')}, {s.get('ref', '?')})")


# --------------------------------------------------------------------------- #
# Public API - what genconfig calls
# --------------------------------------------------------------------------- #

def normalise(mfr_id: str) -> str:
    """
    Canonical form of a caller-supplied id: trimmed and upper-cased.

    Lookups are case-insensitive because `--manufacturer cust` is a typing slip,
    not a different manufacturer - but the config must carry the registry's own
    spelling, so callers emit the id returned by `lookup`/`check`, not their own.
    """
    return (mfr_id or "").strip().upper()


def load(path: Optional[Path] = None, *, reload: bool = False) -> Registry:
    """
    The committed registry snapshot. Cached; raises RegistryError if unusable.
    """
    global _CACHE
    path = Path(path) if path else DATA_FILE
    key = str(path.resolve()) if path.exists() else str(path)
    if not reload and _CACHE is not None and _CACHE[0] == key:
        return _CACHE[1]
    try:
        data = json.loads(path.read_text())
    except FileNotFoundError:
        raise RegistryError(
            f"{path} is missing. Regenerate it with:\n"
            f"    python3 {Path(__file__).name} --refresh --config <config repo>")
    except (OSError, ValueError) as exc:
        raise RegistryError(f"{path} is unreadable: {exc}")
    reg = Registry(data)
    if not len(reg):
        raise RegistryError(f"{path} contains no manufacturers")
    _CACHE = (key, reg)
    return reg


_CACHE: Optional[Tuple[str, Registry]] = None


def lookup(mfr_id: str, *, registry: Optional[Registry] = None) -> Optional[Manufacturer]:
    """The registry entry for `mfr_id`, or None if it is not registered."""
    return (registry or load()).lookup(mfr_id)


def check(mfr_id: str, *, registry: Optional[Registry] = None) -> Check:
    """Validate a caller-supplied id. See `Check` for the fields."""
    return (registry or load()).check(mfr_id)


def is_registered(mfr_id: str, *, registry: Optional[Registry] = None) -> bool:
    """True if `mfr_id` appears in the registry (case-insensitive)."""
    return (registry or load()).lookup(mfr_id) is not None


# --------------------------------------------------------------------------- #
# Parsing the markdown table
# --------------------------------------------------------------------------- #

SEPARATOR_CELL = re.compile(r"^:?-+:?$")


def split_row(line: str) -> List[str]:
    """
    Cells of a markdown table row.

    `|YYRC|JLDZ||` has an empty third cell, so the trailing pipe cannot simply
    be stripped - that would lose the column and make the row look malformed.
    """
    parts = line.split("|")
    if parts and not parts[0].strip():
        parts = parts[1:]
    if parts and not parts[-1].strip():
        parts = parts[:-1]
    return [p.strip() for p in parts]


def parse_markdown(text: str) -> Tuple[Dict[str, Dict[str, str]], List[str]]:
    """
    Parse the registry table.

    Returns (entries, problems). `problems` names every table row that could not
    be read, with its line number - a row is never dropped in silence, because a
    manufacturer missing from the snapshot fails a config that is in fact valid.

    Ids are taken verbatim from the file. A row whose id is not 3-4 uppercase
    characters is still recorded (the registry decides what is registered) and
    additionally reported, so an oddity is visible without being censored.
    """
    entries: Dict[str, Dict[str, str]] = {}
    problems: List[str] = []
    seen_header = False
    in_fence = False

    for n, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence or not line.startswith("|"):
            continue

        cells = split_row(line)
        if all(SEPARATOR_CELL.match(c) for c in cells if c):
            continue                                  # |-|-|-|
        if not seen_header and cells and cells[0].lower() in ("manufacturer id", "id"):
            seen_header = True
            continue

        if len(cells) != 3:
            problems.append(f"line {n}: expected 3 columns, got {len(cells)}")
            continue
        mid, name, url = cells
        if not mid:
            problems.append(f"line {n}: empty manufacturer id")
            continue
        if mid in entries:
            problems.append(f"line {n}: duplicate id {mid} (keeping the first)")
            continue
        if not ID_SHAPE.match(mid):
            problems.append(f"line {n}: id {mid!r} is not 3-4 uppercase characters "
                            f"(recorded anyway)")
        entries[mid] = {"name": name, "url": url}

    if not seen_header:
        problems.append(f"no '|Manufacturer Id|Name|Contact|' header row found")
    return entries, problems


# --------------------------------------------------------------------------- #
# Refresh - regenerate the snapshot from a local config repo
# --------------------------------------------------------------------------- #

def _public_remote(repo: Path) -> str:
    """
    The registry's public home, never a local path.

    A dev machine's clone usually has `origin` pointing at a personal fork and
    `upstream` at betaflight/config; the table's content is upstream's, so
    upstream wins. Anything that is not a public URL - a path, a file:// clone -
    is dropped rather than committed, because this file is published and a
    previous data file leaked a home directory that way.
    """
    for remote in ("upstream", "origin"):
        url = _git(repo, "remote", "get-url", remote)
        if re.match(r"^(https?|ssh|git)://|^git@", url):
            url = re.sub(r"^git@([^:]+):", r"https://\1/", url)
            return re.sub(r"\.git$", "", url)
    return UPSTREAM_REPO


def _git(repo: Path, *args: str) -> str:
    try:
        return subprocess.run(["git", "-C", str(repo), *args],
                              capture_output=True, text=True, timeout=10).stdout.strip()
    except Exception:
        return ""


def _git_bytes(repo: Path, *args: str) -> Optional[bytes]:
    """stdout of a git command, or None if it failed. Bytes, so `git show`
    output hashes to exactly what the file on disk would."""
    try:
        p = subprocess.run(["git", "-C", str(repo), *args],
                           capture_output=True, timeout=10)
    except Exception:
        return None
    return p.stdout if p.returncode == 0 else None


# Refs holding the registry as merged, best first on a tie. Ranked by the date
# of their last change to Manufacturers.md rather than by this order, because a
# fork's origin/master can be either ahead of or behind upstream's.
MASTER_REFS = ("upstream/master", "origin/master", "master")


class Source(NamedTuple):
    text: str                    # the markdown
    meta: Dict[str, object]      # provenance, free of local paths
    where: str                   # human-readable origin, for the console only


def _ref_stamp(repo: Path, ref: str) -> str:
    """Commit time of the registry file at `ref`, or "" if the ref is unknown."""
    return _git(repo, "log", "-1", "--format=%ct", ref, "--", REGISTRY_FILE)


def best_master_ref(repo: Path) -> Optional[str]:
    """The master ref whose Manufacturers.md is newest."""
    scored = [(_ref_stamp(repo, r), -i, r) for i, r in enumerate(MASTER_REFS)]
    scored = [s for s in scored if s[0]]
    if not scored:
        return None
    return max(scored)[2]


def read_registry(target: Path, ref: Optional[str] = None,
                  worktree: bool = False) -> Source:
    """
    Fetch the registry markdown, by default from the repo's master ref.

    Reading the *checked-out* file is the obvious thing and it is wrong. A dev
    machine's config clones sit on submission branches, and one of those may be
    adding a manufacturer that upstream has not merged - snapshotting it would
    bless an id the configurator does not yet know, which is the exact failure
    this module exists to prevent. It also cuts the other way: here, three
    clones on feature branches carried a registry two months newer than the two
    sitting on a stale local master.

    So the merged registry decides, not whatever branch happens to be checked
    out. `worktree=True` overrides, for an unmerged file you are testing.
    """
    target = Path(target)
    if target.is_file():                       # explicit path to a .md
        repo, md = target.parent, target
        worktree = True
    else:
        repo, md = target, target / REGISTRY_FILE

    if not worktree:
        ref = ref or best_master_ref(repo)
        if ref:
            text = _git_bytes(repo, "show", f"{ref}:{REGISTRY_FILE}")
            if text is None:
                raise SystemExit(f"{REGISTRY_FILE} not found at {ref} in {repo}")
            meta = {
                "repo": _public_remote(repo),
                "file": REGISTRY_FILE,
                "ref": ref,
                "rev": _git(repo, "log", "-1", "--format=%h", "--abbrev=9",
                            ref, "--", REGISTRY_FILE),
                "commit_date": _git(repo, "log", "-1", "--format=%cs",
                                    ref, "--", REGISTRY_FILE),
                "sha256": hashlib.sha256(text).hexdigest(),
            }
            return Source(text.decode("utf-8"), meta, f"{repo}  ({ref})")
        # no master ref at all - fall through and say so

    if not md.exists():
        raise SystemExit(f"{md} not found - is {repo} a config repo checkout?")
    raw = md.read_bytes()
    meta = {
        "repo": _public_remote(repo),
        "file": REGISTRY_FILE,
        "ref": "working tree",
        "rev": _git(repo, "log", "-1", "--format=%h", "--abbrev=9", "--", REGISTRY_FILE),
        "commit_date": _git(repo, "log", "-1", "--format=%cs", "--", REGISTRY_FILE),
        "branch": _git(repo, "rev-parse", "--abbrev-ref", "HEAD"),
        "dirty": bool(_git(repo, "status", "--porcelain", "--", REGISTRY_FILE)),
        "sha256": hashlib.sha256(raw).hexdigest(),
    }
    return Source(raw.decode("utf-8"), meta, f"{md}  (working tree)")


def build(target: Path, ref: Optional[str] = None,
          worktree: bool = False) -> Tuple[dict, List[str], str]:
    """Snapshot dict for `data/manufacturers.json`, problems, and origin."""
    src = read_registry(target, ref, worktree)
    entries, problems = parse_markdown(src.text)
    if not entries:
        raise SystemExit(f"No manufacturer rows parsed from {src.where} - wrong file?")
    data = {
        "schema": SCHEMA,
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source": src.meta,
        "reserved": [m for m in RESERVED_IDS if m in entries],
        "manufacturers": {k: entries[k] for k in sorted(entries)},
    }
    return data, problems, src.where


def find_config_repo() -> Optional[Path]:
    """
    Locate a config repo checkout near this one.

    Same hazard as `seed_firmware.find_firmware`: a dev machine carries several
    clones and silently reading a stale one produces a snapshot nobody can
    reproduce. Which branch is checked out does not matter - `read_registry`
    reads the master ref - so rank by how recent that ref's registry is.
    """
    here = Path(__file__).resolve()
    roots = {here.parents[2], *list(here.parents[2].parents)[:1]}
    candidates: List[Path] = []
    for root in roots:
        candidates.append(root / "config")
        candidates.extend(sorted((root / "config").glob("*/config")))

    scored: List[Tuple[str, Path]] = []
    seen = set()
    for c in candidates:
        if not (c / REGISTRY_FILE).exists() or not (c / "configs").is_dir():
            continue
        c = c.resolve()
        if c in seen:
            continue
        seen.add(c)
        ref = best_master_ref(c)
        stamp = _ref_stamp(c, ref) if ref else _git(c, "log", "-1", "--format=%ct",
                                                    "--", REGISTRY_FILE)
        scored.append((stamp or "0", c))
    if not scored:
        return None
    scored.sort(key=lambda t: (t[0], str(t[1])), reverse=True)
    return scored[0][1]


def diff_snapshots(old: Optional[dict], new: dict) -> List[str]:
    """
    Human-readable delta between the committed snapshot and a fresh one.

    Printed before writing, so a refresh that quietly drops half the registry is
    visible rather than merged.
    """
    if not old:
        return [f"+ new file, {len(new['manufacturers'])} manufacturers"]
    a, b = old.get("manufacturers", {}), new["manufacturers"]
    out = [f"+ {k}  {b[k]['name']}" for k in sorted(set(b) - set(a))]
    out += [f"- {k}  {a[k]['name']}" for k in sorted(set(a) - set(b))]
    out += [f"~ {k}  {a[k]['name']!r} -> {b[k]['name']!r}"
            for k in sorted(set(a) & set(b)) if a[k] != b[k]]
    return out or ["  no change to any manufacturer row"]


def refresh(repo: Optional[Path] = None,
            out: Optional[Path] = None,
            *, ref: Optional[str] = None, worktree: bool = False,
            quiet: bool = False, dry_run: bool = False) -> Tuple[dict, List[str]]:
    """
    Regenerate the snapshot from a local config repo. Returns (data, problems).
    """
    repo = Path(repo) if repo else find_config_repo()
    if not repo:
        raise SystemExit("Could not locate a config repo checkout. "
                         "Pass --config PATH.")
    out = Path(out) if out else DATA_FILE
    data, problems, where = build(repo, ref, worktree)

    old = None
    if out.exists():
        try:
            old = json.loads(out.read_text())
        except ValueError:
            old = None

    if not quiet:
        print(f"Reading {where}")
        for line in diff_snapshots(old, data):
            print(f"  {line}")
        for p in problems:
            print(f"  ! {p}", file=sys.stderr)

    if not dry_run:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(data, indent=1, sort_keys=False) + "\n")
        if not quiet:
            src = data["source"]
            print(f"\n{len(data['manufacturers'])} manufacturers "
                  f"({len(data['reserved'])} reserved), "
                  f"{len(problems)} unreadable row(s)")
            print(f"source {src['repo']}/{src['file']} @ {src['rev']} "
                  f"({src['commit_date']}, {src['ref']}"
                  f"{', dirty' if src.get('dirty') else ''})")
            print(f"wrote {out}  ({out.stat().st_size / 1024:.0f} KB)")
    return data, problems


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

def _report(ids: Sequence[str], reg: Registry) -> int:
    bad = 0
    for raw in ids:
        res = reg.check(raw)
        if res.ok:
            entry = reg.lookup(res.id)
            tag = "  [reserved]" if res.reserved else ""
            print(f"OK   {res.id}  {entry.name}{(' - ' + entry.url) if entry.url else ''}{tag}")
        else:
            bad += 1
            print(f"FAIL {raw}  {res.message()}")
    return 1 if bad else 0


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("ids", nargs="*", help="manufacturer ids to validate")
    ap.add_argument("--refresh", action="store_true",
                    help="regenerate the snapshot from a local config repo")
    ap.add_argument("--config", type=Path,
                    help="config repo checkout (or the Manufacturers.md path)")
    ap.add_argument("--ref", help="git ref to read the registry from "
                                  "(default: the newest of %s)" % "/".join(MASTER_REFS))
    ap.add_argument("--worktree", action="store_true",
                    help="read the checked-out file instead of a master ref - "
                         "only for an unmerged registry you are testing")
    ap.add_argument("--out", type=Path, default=DATA_FILE)
    ap.add_argument("--list", action="store_true", help="print every registered id")
    ap.add_argument("--dry-run", action="store_true",
                    help="with --refresh: show the diff, write nothing")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    if args.refresh:
        _, problems = refresh(args.config, args.out,
                              ref=args.ref, worktree=args.worktree,
                              quiet=args.quiet, dry_run=args.dry_run)
        return 1 if problems else 0

    try:
        reg = load(args.out)
    except RegistryError as exc:
        print(exc, file=sys.stderr)
        return 2

    if args.list:
        for m in sorted(reg.ids()):
            e = reg.lookup(m)
            print(f"{m}  {e.name}{'  [reserved]' if e.reserved else ''}")
        return 0

    if args.ids:
        return _report(args.ids, reg)

    print(reg.provenance())
    print(f"snapshot generated {reg.generated}, schema {reg.schema}")
    print(f"reserved: {', '.join(m for m in reg.ids() if reg.lookup(m).reserved)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
